In [1]:
#import libraries
import pandas as pd
import numpy as np

In [2]:
#load dataset
df=pd.read_excel('/content/sample_data/supply_chain_visibility_dataset raw.xlsx')

In [3]:
#view Dataset
df.head()

,Order_ID,Customer_ID,Product_ID,Supplier,Warehouse,Order_Date,Dispatch_Date,Delivery_Date,Expected_Delivery_Date,Delivery_Status,Delay_Days,Shipping_Mode,Transportation_Cost,Order_Value
0,ORD00001,CUST0164,PROD008,Apex Freight Solutions,WH-Kolkata,2025-05-06,2025-05-07,2025-05-13,2025-05-14,Early,0,Rail,962.82,41248.57
1,ORD00002,CUST0229,PROD035,BlueDart Logistics,WH-Bengaluru,2025-01-17,2025-01-18,2025-01-27,2025-01-31,Early,0,Sea,353.05,31310.61
2,ORD00003,CUST0007,PROD036,Delta Cargo Movers,WH-Kolkata,2025-04-23,2025-04-25,2025-05-12,2025-05-07,Delayed,5,Sea,394.73,52419.42
3,ORD00004,CUST0195,PROD052,Continental Supply Co.,WH-Kolkata,2025-06-24,2025-06-26,2025-07-06,2025-07-08,Early,0,Sea,350.72,46282.66
4,ORD00005,CUST0027,PROD006,Global Link Suppliers,WH-Hyderabad,2025-06-26,2025-06-29,2025-07-07,2025-07-04,Delayed,3,Rail,1026.42,44324.44

In [4]:
df.tail()

,Order_ID,Customer_ID,Product_ID,Supplier,Warehouse,Order_Date,Dispatch_Date,Delivery_Date,Expected_Delivery_Date,Delivery_Status,Delay_Days,Shipping_Mode,Transportation_Cost,Order_Value
995,ORD00996,CUST0063,PROD059,Apex Freight Solutions,WH-Pune,2025-10-02,2025-10-04,2025-10-13,2025-10-08,Delayed,5,Road,578.28,16335.96
996,ORD00997,CUST0162,PROD051,Everest Trading Partners,WH-Pune,2025-09-18,2025-09-21,2025-09-27,2025-09-24,Delayed,3,Road,651.09,6721.65
997,ORD00998,CUST0121,PROD051,Skyline Wholesale Group,WH-Hyderabad,2025-09-18,2025-09-20,2025-09-29,2025-09-24,Delayed,5,Road,1458.91,45565.90
998,ORD00999,CUST0096,PROD032,Ironclad Vendors,WH-Delhi,2025-06-14,2025-06-17,2025-06-22,2025-06-20,Delayed,2,Road,1030.57,30031.23
999,ORD01000,CUST0245,PROD032,Horizon Materials Inc.,WH-Mumbai,2025-11-23,2025-11-26,2025-12-14,2025-12-07,Delayed,7,Sea,225.62,14732.52

In [5]:
df.sample(5)

,Order_ID,Customer_ID,Product_ID,Supplier,Warehouse,Order_Date,Dispatch_Date,Delivery_Date,Expected_Delivery_Date,Delivery_Status,Delay_Days,Shipping_Mode,Transportation_Cost,Order_Value
895,ORD00896,CUST0202,PROD012,Global Link Suppliers,WH-Hyderabad,2025-08-02,2025-08-05,2025-08-08,2025-08-05,Delayed,3,Air,2441.84,43997.49
893,ORD00894,CUST0235,PROD003,Ironclad Vendors,WH-Hyderabad,2025-07-31,2025-08-01,2025-08-16,2025-08-14,Delayed,2,Sea,662.60,34971.74
925,ORD00926,CUST0089,PROD057,Global Link Suppliers,WH-Pune,2025-06-04,2025-06-05,2025-06-08,2025-06-10,Early,0,Road,1044.92,24619.63
365,ORD00366,CUST0163,PROD054,Apex Freight Solutions,WH-Mumbai,2025-12-03,2025-12-05,2025-12-08,2025-12-06,Delayed,2,Air,1811.85,32729.24
28,ORD00029,CUST0013,PROD042,Ironclad Vendors,WH-Pune,2025-02-17,2025-02-18,2025-02-20,2025-02-20,On Time,0,Air,2719.24,29918.79

In [6]:
df.iloc[10:21]

,Order_ID,Customer_ID,Product_ID,Supplier,Warehouse,Order_Date,Dispatch_Date,Delivery_Date,Expected_Delivery_Date,Delivery_Status,Delay_Days,Shipping_Mode,Transportation_Cost,Order_Value
10,ORD00011,CUST0017,PROD014,Skyline Wholesale Group,NaN,2025-04-19,2025-04-22,2025-05-03,2025-04-27,Delayed,6,Rail,656.07,55043.76
11,ORD00012,CUST0118,PROD010,Everest Trading Partners,WH-Chennai,2025-10-15,2025-10-18,2025-10-23,2025-10-21,Delayed,2,Road,1296.42,26849.16
12,ORD00013,CUST0150,PROD026,FastTrack Distributors,WH-Chennai,2025-09-18,2025-09-20,2025-09-23,2025-09-24,Early,0,Road,NaN,51943.97
13,ORD00014,CUST0040,PROD041,Continental Supply Co.,WH-Pune,2025-11-02,2025-11-03,2025-11-17,2025-11-16,Delayed,1,Sea,467.13,59775.04
14,ORD00015,CUST0136,PROD017,Ironclad Vendors,WH-Pune,2025-12-15,2025-12-18,2025-12-19,2025-12-18,Delayed,1,Air,3545.13,33144.28
15,ORD00016,CUST0069,PROD050,FastTrack Distributors,WH-Hyderabad,2025-08-11,2025-08-12,2025-08-23,2025-08-19,Delayed,4,Rail,302.92,43881.34
16,ORD00017,CUST0185,PROD017,Ironclad Vendors,WH-Pune,2025-09-17,2025-09-18,2025-09-27,2025-09-23,Delayed,4,Road,1150.36,50816.82
17,ORD00018,CUST0130,PROD039,Delta Cargo Movers,WH-Chennai,NaT,2025-03-27,2025-03-31,2025-04-01,Early,0,Rail,839.05,30339.13
18,ORD00019,CUST0029,PROD060,FastTrack Distributors,WH-Pune,2025-05-03,2025-05-04,2025-05-11,2025-05-11,On Time,0,Rail,1090.21,56923.07
19,NaN,CUST0022,PROD047,Horizon Materials Inc.,WH-Pune,2025-09-30,2025-10-01,2025-10-03,2025-10-03,On Time,0,Air,3479.25,56917.22
20,ORD00021,CUST0043,PROD017,Ironclad Vendors,WH-Pune,2025-04-19,2025-04-22,2025-05-12,2025-05-03,Delayed,9,Sea,710.95,13666.76

In [7]:
df.shape

(1000, 14)

In [8]:
df.columns

Index(['Order_ID', 'Customer_ID', 'Product_ID', 'Supplier', 'Warehouse',
       'Order_Date', 'Dispatch_Date', 'Delivery_Date',
       'Expected_Delivery_Date', 'Delivery_Status', 'Delay_Days',
       'Shipping_Mode', 'Transportation_Cost', 'Order_Value'],
      dtype='object')

In [9]:
print("Row : ",df.shape[0])
print("Col : ",df.shape[1])

Row :  1000
Col :  14

In [10]:
df[['Expected_Delivery_Date']]

    Expected_Delivery_Date
0               2025-05-14
1               2025-01-31
2               2025-05-07
3               2025-07-08
4               2025-07-04
..                     ...
995             2025-10-08
996             2025-09-24
997             2025-09-24
998             2025-06-20
999             2025-12-07

[1000 rows x 1 columns]

In [11]:
df.describe()

,Order_Date,Dispatch_Date,Delivery_Date,Expected_Delivery_Date,Delay_Days,Transportation_Cost,Order_Value
count,992,995,1000,996,1000.00000,998.000000,999.000000
mean,2025-07-06 13:25:38.709677568,2025-07-08 15:42:09.045226240,2025-07-16 05:22:33.600000,2025-07-14 07:44:05.783132672,185.66300,1297.392385,30965.109800
min,2025-01-02 00:00:00,2025-01-04 00:00:00,2025-01-06 00:00:00,2025-01-06 00:00:00,0.00000,204.630000,2050.320000
25%,2025-04-06 00:00:00,2025-04-07 00:00:00,2025-04-13 00:00:00,2025-04-12 00:00:00,0.00000,583.430000,17266.810000
50%,2025-07-05 12:00:00,2025-07-08 00:00:00,2025-07-15 00:00:00,2025-07-13 12:00:00,2.00000,848.910000,30560.480000
75%,2025-10-07 00:00:00,2025-10-09 00:00:00,2025-10-19 00:00:00,2025-10-16 06:00:00,4.00000,1536.425000,44195.780000
max,2025-12-31 00:00:00,2026-01-03 00:00:00,2026-01-22 00:00:00,2026-01-14 00:00:00,45982.00000,4498.720000,59871.650000
std,NaN,NaN,NaN,NaN,2897.06269,1085.456083,16204.667655

In [12]:
df.info() #Check Data Types

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Order_ID                997 non-null    object
 1   Customer_ID             992 non-null    object
 2   Product_ID              993 non-null    object
 3   Supplier                992 non-null    object
 4   Warehouse               992 non-null    object
 5   Order_Date              992 non-null    datetime64[ns]
 6   Dispatch_Date           995 non-null    datetime64[ns]
 7   Delivery_Date           1000 non-null   datetime64[ns]
 8   Expected_Delivery_Date  996 non-null    datetime64[ns]
 9   Delivery_Status         993 non-null    object
 10  Delay_Days              1000 non-null   int64
 11  Shipping_Mode           998 non-null    object
 12  Transportation_Cost     998 non-null    float64
 13  Order_Value             999 non-null    float64
dtypes: datetime64[ns](4), float64(2), int64(1), object(7)
memory usage: 109.5+ KB

In [13]:
#Check Missing Values
df.isnull().sum()

Order_ID                  3
Customer_ID               8
Product_ID                7
Supplier                  8
Warehouse                 8
Order_Date                8
Dispatch_Date             5
Delivery_Date             0
Expected_Delivery_Date    4
Delivery_Status           7
Delay_Days                0
Shipping_Mode             2
Transportation_Cost       2
Order_Value               1
dtype: int64

In [14]:
#Check Duplicate Records
df.duplicated().sum()
#df.drop_duplicates(inplace=True)

np.int64(0)

In [15]:
#Fix Column Names
df.rename(columns={
    'Transportation_Cost':'Tran-Cost',
    'Delivery_Status':'Status',
    'Expected_Delivery_Date':'EDD'

},inplace=True)

In [16]:
#Remove Extra Spaces
df['Customer_ID']=df['Customer_ID'].str.strip()
df['Product_ID']=df['Product_ID'].str.strip()
df['Supplier']=df['Supplier'].str.strip()
df['Warehouse']=df['Warehouse'].str.strip()
df['Status']=df['Status'].str.strip()
df['Shipping_Mode']=df['Shipping_Mode'].str.strip()

In [17]:
#Standardize Text
df['Supplier'].str.title()
df['Shipping_Mode'].str.title()
df['Status'].str.title()
print(df['Supplier'])
print(df['Shipping_Mode'])
print(df['Status'])

0        Apex Freight Solutions
1            BlueDart Logistics
2            Delta Cargo Movers
3        Continental Supply Co.
4         Global Link Suppliers
                 ...
995      Apex Freight Solutions
996    Everest Trading Partners
997     Skyline Wholesale Group
998            Ironclad Vendors
999      Horizon Materials Inc.
Name: Supplier, Length: 1000, dtype: object
0      Rail
1       Sea
2       Sea
3       Sea
4      Rail
       ...
995    Road
996    Road
997    Road
998    Road
999     Sea
Name: Shipping_Mode, Length: 1000, dtype: object
0        Early
1        Early
2      Delayed
3        Early
4      Delayed
        ...
995    Delayed
996    Delayed
997    Delayed
998    Delayed
999    Delayed
Name: Status, Length: 1000, dtype: object

In [18]:
df.isnull().sum()

Order_ID         3
Customer_ID      8
Product_ID       7
Supplier         8
Warehouse        8
Order_Date       8
Dispatch_Date    5
Delivery_Date    0
EDD              4
Status           7
Delay_Days       0
Shipping_Mode    2
Tran-Cost        2
Order_Value      1
dtype: int64

In [19]:
df['Order_ID']

0      ORD00001
1      ORD00002
2      ORD00003
3      ORD00004
4      ORD00005
         ...
995    ORD00996
996    ORD00997
997    ORD00998
998    ORD00999
999    ORD01000
Name: Order_ID, Length: 1000, dtype: object

In [20]:
#fill oder-id missing values
df["Order_ID"] = "ORD" + (df.index + 1).astype(str).str.zfill(5)
df['Order_ID'].isnull().sum()

np.int64(0)

In [21]:
df.isnull().sum()

Order_ID         0
Customer_ID      8
Product_ID       7
Supplier         8
Warehouse        8
Order_Date       8
Dispatch_Date    5
Delivery_Date    0
EDD              4
Status           7
Delay_Days       0
Shipping_Mode    2
Tran-Cost        2
Order_Value      1
dtype: int64

In [22]:
#fill missing value of order_id
df[['Status']]

      Status
0      Early
1      Early
2    Delayed
3      Early
4    Delayed
..       ...
995  Delayed
996  Delayed
997  Delayed
998  Delayed
999  Delayed

[1000 rows x 1 columns]

In [23]:
df.groupby("Status")["Delay_Days"].describe() #groups the data by Status and shows statistics for Delay_Days

         count        mean         std  min  25%  50%  75%      max
Status
Delayed  677.0  274.228951  3518.36655  1.0  2.0  3.0  4.0  45982.0
Early    182.0    0.000000     0.00000  0.0  0.0  0.0  0.0      0.0
On Time  134.0    0.000000     0.00000  0.0  0.0  0.0  0.0      0.0

In [ ]:
df[df["Status"] == "Early"][
    [
        "EDD",
        "Delivery_Date",
        "Delay_Days"
    ]
].head(20)

          EDD Delivery_Date  Delay_Days
0  2025-05-14    2025-05-13           0
1  2025-01-31    2025-01-27           0
3  2025-07-08    2025-07-06           0
6  2025-02-18    2025-02-16           0
9  2025-02-06    2025-02-03           0
12 2025-09-24    2025-09-23           0
17 2025-04-01    2025-03-31           0
21 2025-03-17    2025-03-15           0
25 2025-09-11    2025-09-08           0
30 2025-04-04    2025-04-03           0
35 2025-11-29    2025-11-27           0
37 2025-12-14    2025-12-13           0
43 2025-11-28    2025-11-27           0
46 2025-05-05    2025-05-02           0
48 2025-10-31    2025-10-30           0
50 2025-07-12    2025-07-11           0
52 2025-12-27    2025-12-26           0
55 2025-05-04    2025-05-03           0
61 2025-05-27    2025-05-26           0
63 2025-08-15    2025-08-13           0

In [ ]:
#Calculate the correct delay
df["Delay_Days"] = (
    df["Delivery_Date"] - df["EDD"]
).dt.days
df['Delay_Days'].describe()

count    996.000000
mean       1.808233
std        2.654734
min       -5.000000
25%        0.000000
50%        2.000000
75%        4.000000
max        9.000000
Name: Delay_Days, dtype: float64

In [ ]:
df[df['Status']=='Early']['Delay_Days'].head(3)

0   -1.0
1   -4.0
3   -2.0
Name: Delay_Days, dtype: float64

In [ ]:
#Recreate the Status column
df.loc[df["Delay_Days"] < 0, "Status"] = "Early"

df.loc[df["Delay_Days"] == 0, "Status"] = "On Time"

df.loc[df["Delay_Days"] > 0, "Status"] = "Delayed"
df[['Status']]

      Status
0      Early
1      Early
2    Delayed
3      Early
4    Delayed
..       ...
995  Delayed
996  Delayed
997  Delayed
998  Delayed
999  Delayed

[1000 rows x 1 columns]

In [ ]:
df['Status'].isnull().sum()

np.int64(0)

In [ ]:
df[['Customer_ID']]

    Customer_ID
0      CUST0164
1      CUST0229
2      CUST0007
3      CUST0195
4      CUST0027
..          ...
995    CUST0063
996    CUST0162
997    CUST0121
998    CUST0096
999    CUST0245

[1000 rows x 1 columns]

In [ ]:
#fill Fill missing Order_Date
#check how many days usually pass between ordering and dispatch.
processing_days = (
    df["Dispatch_Date"] - df["Order_Date"]
).dt.days

print(processing_days.value_counts().sort_index())

1.0    321
2.0    336
3.0    330
Name: count, dtype: int64

In [ ]:
#If most orders are dispatched after 1 day? answer-find mode
processing_mode = processing_days.mode()[0]

print(processing_mode)

2.0

In [ ]:
#Fill missing Order_Date
mask = df["Order_Date"].isna()

df.loc[mask, "Order_Date"] = (
    df.loc[mask, "Dispatch_Date"] - pd.to_timedelta(processing_mode, unit="D")
)
df['Order_Date'].isnull().sum()

np.int64(0)

In [ ]:
#Fill missing Dispatch_Date
mask = df["Dispatch_Date"].isna()

df.loc[mask, "Dispatch_Date"] = (
    df.loc[mask, "Order_Date"] + pd.to_timedelta(processing_mode, unit="D")
)
df['Dispatch_Date'].isnull().sum()

np.int64(0)

In [ ]:
#Expected Delivery time
expected_days = (
    df["EDD"] - df["Order_Date"]
).dt.days

print(expected_days.value_counts().sort_index())

2.0       1
3.0     237
5.0       1
6.0     247
7.0       1
8.0     243
13.0      1
14.0    264
15.0      1
Name: count, dtype: int64

In [ ]:
#Find the mode-doesn't have a single expected delivery time

expected_mode = expected_days.mode()[0]
print(expected_mode)

14.0

In [ ]:
#Fill missing EDD
mask = df["EDD"].isna()

df.loc[mask, "EDD"] = (
    df.loc[mask, "Order_Date"] + pd.to_timedelta(expected_mode, unit="D")
)
df['EDD'].isnull().sum()

np.int64(0)

In [ ]:
#Recalculate Delay_Days again
df["Delay_Days"] = (
    df["Delivery_Date"] - df["EDD"]
).dt.days
df['Delay_Days']

0     -1
1     -4
2      5
3     -2
4      3
      ..
995    5
996    3
997    5
998    2
999    7
Name: Delay_Days, Length: 1000, dtype: int64

In [ ]:
#Recreate Status
df.loc[df["Delay_Days"] < 0, "Status"] = "Early"

df.loc[df["Delay_Days"] == 0, "Status"] = "On Time"

df.loc[df["Delay_Days"] > 0, "Status"] = "Delayed"
df['Status']

0        Early
1        Early
2      Delayed
3        Early
4      Delayed
        ...
995    Delayed
996    Delayed
997    Delayed
998    Delayed
999    Delayed
Name: Status, Length: 1000, dtype: object

In [ ]:
df[[
    "Order_Date",
    "Dispatch_Date",
    "EDD",
    "Delivery_Date",
    "Delay_Days",
    "Status"
]].isnull().sum()

Order_Date       0
Dispatch_Date    0
EDD              0
Delivery_Date    0
Delay_Days       0
Status           0
dtype: int64

In [ ]:
#fill Tran-Cost	and Order_Value
df['Tran-Cost']=df['Tran-Cost'].fillna(df['Tran-Cost'].median())

df['Tran-Cost'].isnull().sum()

np.int64(0)

In [ ]:

df['Order_Value']=df['Order_Value'].fillna(df['Order_Value'].median())
df['Order_Value'].isnull().sum()

np.int64(0)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       1000 non-null   object
 1   Customer_ID    992 non-null    object
 2   Product_ID     993 non-null    object
 3   Supplier       992 non-null    object
 4   Warehouse      992 non-null    object
 5   Order_Date     1000 non-null   datetime64[ns]
 6   Dispatch_Date  1000 non-null   datetime64[ns]
 7   Delivery_Date  1000 non-null   datetime64[ns]
 8   EDD            1000 non-null   datetime64[ns]
 9   Status         1000 non-null   object
 10  Delay_Days     1000 non-null   int64
 11  Shipping_Mode  998 non-null    object
 12  Tran-Cost      1000 non-null   float64
 13  Order_Value    1000 non-null   float64
dtypes: datetime64[ns](4), float64(2), int64(1), object(7)
memory usage: 109.5+ KB

In [ ]:
#Filter Data
df[df['Status']=='On Time']

,Order_ID,Customer_ID,Product_ID,Supplier,Warehouse,Order_Date,Dispatch_Date,Delivery_Date,EDD,Status,Delay_Days,Shipping_Mode,Tran-Cost,Order_Value
18,ORD00019,CUST0029,PROD060,FastTrack Distributors,WH-Pune,2025-05-03,2025-05-04,2025-05-11,2025-05-11,On Time,0,Rail,1090.21,56923.07
19,ORD00020,CUST0022,PROD047,Horizon Materials Inc.,WH-Pune,2025-09-30,2025-10-01,2025-10-03,2025-10-03,On Time,0,Air,3479.25,56917.22
26,ORD00027,CUST0026,PROD004,Global Link Suppliers,WH-Kolkata,2025-02-25,2025-02-26,2025-03-05,2025-03-05,On Time,0,Rail,471.19,28019.59
28,ORD00029,CUST0013,PROD042,Ironclad Vendors,WH-Pune,2025-02-17,2025-02-18,2025-02-20,2025-02-20,On Time,0,Air,2719.24,29918.79
29,ORD00030,CUST0222,PROD026,Apex Freight Solutions,WH-Chennai,2025-01-02,2025-01-04,2025-01-16,2025-01-16,On Time,0,Sea,848.56,47537.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
936,ORD00937,CUST0242,PROD036,FastTrack Distributors,WH-Hyderabad,2025-02-26,2025-02-27,2025-03-12,2025-03-12,On Time,0,Sea,600.24,4336.36
944,ORD00945,CUST0148,PROD049,Apex Freight Solutions,WH-Bengaluru,2025-09-01,2025-09-04,2025-09-07,2025-09-07,On Time,0,Road,544.34,56298.54
950,ORD00951,CUST0229,PROD021,Everest Trading Partners,WH-Delhi,2025-01-27,2025-01-28,2025-01-30,2025-01-30,On Time,0,Air,3756.40,35989.69
956,ORD00957,CUST0070,PROD039,Everest Trading Partners,WH-Pune,2025-06-29,2025-07-02,2025-07-13,2025-07-13,On Time,0,Sea,609.61,31599.05
962,ORD00963,CUST0020,PROD035,Apex Freight Solutions,WH-Pune,2025-12-11,2025-12-12,2025-12-25,2025-12-25,On Time,0,Sea,880.43,23829.83

In [ ]:
#Sort Data
df.srot_values(df['Tran-Cost'])

0        Apex Freight Solutions
1            BlueDart Logistics
2            Delta Cargo Movers
3        Continental Supply Co.
4         Global Link Suppliers
                 ...
995      Apex Freight Solutions
996    Everest Trading Partners
997     Skyline Wholesale Group
998            Ironclad Vendors
999      Horizon Materials Inc.
Name: Supplier, Length: 1000, dtype: object
0      Rail
1       Sea
2       Sea
3       Sea
4      Rail
       ...
995    Road
996    Road
997    Road
998    Road
999     Sea
Name: Shipping_Mode, Length: 1000, dtype: object

In [ ]:
#Save clean dataset
df.to_csv('/content/sample_data/preproDataset_supplyChain.csv')
print("Data preprocessing completed successfully")

Data preprocessing completed successfully